---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list: ["recipe[hipchat-test]"]
  attributes:
    hipchat_test:
      room: <%= ENV['HIPCHAT_TEST_ROOM'] %>
      v1_token: <%= ENV['HIPCHAT_TEST_V1_TOKEN'] %>
      v2_token: <%= ENV['HIPCHAT_TEST_V2_TOKEN'] %>

- name: handler
  run_list: ["recipe[hipchat-test::handler]"]
  attributes:
    hipchat:
      handler:
        enabled: true
        room: <%= ENV['HIPCHAT_TEST_ROOM'] %>
        token: <%= ENV['HIPCHAT_TEST_V2_TOKEN'] %>
